#Game TAGS
windowrule = match:class org.prismlauncher.PrismLauncher, tag +gamestore
windowrule = match:class heroic, tag +gamestore
windowrule = match:class steam, tag +steam 
windowrule = match:class ^(steam_app_).*$, tag +game
windowrule = match:title ^(Minecraft).*$, tag +game
windowrule = match:class rocketleague.exe,tag +game
#App tags 
windowrule = match:class discord,tag +message
windowrule = match:class firefox,tag +browser
windowrule = match:class com.obsproject.Studio,tag +record
windowrule = match:class mpv,tag +video
windowrule = match:class kitty,tag +term

#Workspaces
windowrule = match:tag record,workspace 1
windowrule = match:tag term,workspace 2
windowrule = match:tag browser,workspace 3
windowrule = match:tag gamestore ,workspace 4
windowrule = match:tag steam,workspace 4
windowrule = match:tag message,workspace 5
windowrule = match:tag video,workspace 6
windowrule = match:tag game,workspace 7
#Popup windows
windowrule = match:title Steam Settings, tag +popup
windowrule = match:title Friends List, tag +popup
windowrule = match:title ^(Console window).*$,tag +popup




#Float windows
windowrule = match:class steam, float on
windowrule = match:class nemo,float on
windowrule = match:tag popup,float on
windowrule = match:title BakkesModInjectorCpp,float on 

#Exceptions

windowrule = match:title Steam,tile on




